config/routes.rb
Rails.application.routes.draw do
  resources :leagues do
    resources :teams, shallow: true
    resources :alleys, shallow: true
  end

  resources :teams do
    resources :bowlers, shallow: true
  end

  resources :alleys do
    resources :addresses, shallow: true
  end

  root to: 'home#index'
  devise_for :users

end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :alley
  belongs_to :administrator, class_name: 'User', foreign_key: 'administrator_id'
  has_many :teams
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :start_date, :end_date, :day, :start_time, :practice, :alley_id)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.haml
= simple_form_for(@league) do |f|
  = f.error_notification

  .row
    .columns.medium-6
        = f.input :name
        = f.input :start_date
        = f.input :end_date
        = f.input :day
        = f.input :time
        = f.input :practice
        = f.association :alley
  .row
    .columns.medium-6
      .form-actions
        = f.button :submit, class: 'button'

app/views/leagues/edit.html.haml
%h1 Editing league

= render 'form'

= link_to 'Show', @league
\|
= link_to 'Back', leagues_path

app/views/leagues/index.html.haml
%h1 Listing leagues

%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Day
      %th Time
      %th Practice
      %th Alley
      %th
      %th
      %th

  %tbody
    - @leagues.each do |league|
      %tr
        %td= league.name
        %td= league.start_date
        %td= league.end_date
        %td= league.day
        %td= league.time
        %td= league.practice
        %td= league.alley
        %td= link_to 'Show', league
        %td= link_to 'Edit', edit_league_path(league)
        %td= link_to 'Destroy', league, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New League', new_league_path

app/views/leagues/new.html.haml
%h1 New league

= render 'form'

= link_to 'Back', leagues_path

app/views/leagues/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @league.name
%p
  %b Start date:
  = @league.start_date
%p
  %b End date:
  = @league.end_date
%p
  %b Day:
  = @league.day
%p
  %b Time:
  = @league.time
%p
  %b Practice:
  = @league.practice
%p
  %b Alley:
  = @league.alley

= link_to 'Edit', edit_league_path(@league)
\|
= link_to 'Back', leagues_path