config/routes.rb
Rails.application.routes.draw do
  resources :leagues do
    resources :teams, shallow: true
    resources :alleys, shallow: true
  end

  resources :teams do
    resources :bowlers, shallow: true
  end

  resources :alleys do
    resources :addresses, shallow: true
  end

  root to: 'home#index'
  devise_for :users

end

app/models/alley.rb
class Alley < ActiveRecord::Base
  belongs_to :address
  has_many :leagues
end

app/controllers/alleys_controller.rb
class AlleysController < ApplicationController
  before_action :set_alley, only: [:show, :edit, :update, :destroy]

  # GET /alleys
  # GET /alleys.json
  def index
    @alleys = Alley.all
  end

  # GET /alleys/1
  # GET /alleys/1.json
  def show
  end

  # GET /alleys/new
  def new
    @alley = Alley.new
  end

  # GET /alleys/1/edit
  def edit
  end

  # POST /alleys
  # POST /alleys.json
  def create
    @alley = Alley.new(alley_params)

    respond_to do |format|
      if @alley.save
        format.html { redirect_to @alley, notice: 'Alley was successfully created.' }
        format.json { render :show, status: :created, location: @alley }
      else
        format.html { render :new }
        format.json { render json: @alley.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alleys/1
  # PATCH/PUT /alleys/1.json
  def update
    respond_to do |format|
      if @alley.update(alley_params)
        format.html { redirect_to @alley, notice: 'Alley was successfully updated.' }
        format.json { render :show, status: :ok, location: @alley }
      else
        format.html { render :edit }
        format.json { render json: @alley.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alleys/1
  # DELETE /alleys/1.json
  def destroy
    @alley.destroy
    respond_to do |format|
      format.html { redirect_to alleys_url, notice: 'Alley was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alley
      @alley = Alley.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alley_params
      params.require(:alley).permit(:name, :address_id)
    end
end

app/helpers/alleys_helper.rb
module AlleysHelper
end

app/views/alleys/_form.html.haml
= simple_form_for(@alley) do |f|
  = f.error_notification

  .row
    .columns.medium-6
        = f.input :name
        = f.input :address_id
  .row
    .columns.medium-6
      .form-actions
        = f.button :submit, class: 'button'

app/views/alleys/edit.html.haml
%h1 Editing alley

= render 'form'

= link_to 'Show', @alley
\|
= link_to 'Back', alleys_path

app/views/alleys/index.html.haml
%h1 Listing alleys

%table
  %thead
    %tr
      %th Name
      %th Address
      %th
      %th
      %th

  %tbody
    - @alleys.each do |alley|
      %tr
        %td= alley.name
        %td= alley.address_id
        %td= link_to 'Show', alley
        %td= link_to 'Edit', edit_alley_path(alley)
        %td= link_to 'Destroy', alley, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Alley', new_alley_path

app/views/alleys/new.html.haml
%h1 New alley

= render 'form'

= link_to 'Back', alleys_path

app/views/alleys/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @alley.name
%p
  %b Address:
  = @alley.address_id

= link_to 'Edit', edit_alley_path(@alley)
\|
= link_to 'Back', alleys_path