config/routes.rb
Rails.application.routes.draw do
  resources :leagues do
    resources :teams, shallow: true
    resources :alleys, shallow: true
  end

  resources :teams do
    resources :bowlers, shallow: true
  end

  resources :alleys do
    resources :addresses, shallow: true
  end

  root to: 'home#index'
  devise_for :users

end

app/models/bowler.rb
class Bowler < ActiveRecord::Base
  has_and_belongs_to_many :teams, join_table: :bowlers_teams
end

app/controllers/bowlers_controller.rb
class BowlersController < ApplicationController
  before_action :set_bowler, only: [:show, :edit, :update, :destroy]

  # GET /bowlers
  # GET /bowlers.json
  def index
    @bowlers = Bowler.all
  end

  # GET /bowlers/1
  # GET /bowlers/1.json
  def show
  end

  # GET /bowlers/new
  def new
    @bowler = Bowler.new
  end

  # GET /bowlers/1/edit
  def edit
  end

  # POST /bowlers
  # POST /bowlers.json
  def create
    @bowler = Bowler.new(bowler_params)

    respond_to do |format|
      if @bowler.save
        format.html { redirect_to @bowler, notice: 'Bowler was successfully created.' }
        format.json { render :show, status: :created, location: @bowler }
      else
        format.html { render :new }
        format.json { render json: @bowler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bowlers/1
  # PATCH/PUT /bowlers/1.json
  def update
    respond_to do |format|
      if @bowler.update(bowler_params)
        format.html { redirect_to @bowler, notice: 'Bowler was successfully updated.' }
        format.json { render :show, status: :ok, location: @bowler }
      else
        format.html { render :edit }
        format.json { render json: @bowler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bowlers/1
  # DELETE /bowlers/1.json
  def destroy
    @bowler.destroy
    respond_to do |format|
      format.html { redirect_to bowlers_url, notice: 'Bowler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bowler
      @bowler = Bowler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bowler_params
      params.require(:bowler).permit(:name, :usbc_number)
    end
end

app/helpers/bowlers_helper.rb
module BowlersHelper
end

app/views/bowlers/_form.html.haml
= simple_form_for(@bowler) do |f|
  = f.error_notification

  .row
    .columns.medium-6
        = f.input :name
        = f.input :usbc_number
  .row
    .columns.medium-6
      .form-actions
        = f.button :submit, class: 'button'

app/views/bowlers/edit.html.haml
%h1 Editing bowler

= render 'form'

= link_to 'Show', @bowler
\|
= link_to 'Back', bowlers_path

app/views/bowlers/index.html.haml
%h1 Listing bowlers

%table
  %thead
    %tr
      %th Name
      %th Usbc number
      %th
      %th
      %th

  %tbody
    - @bowlers.each do |bowler|
      %tr
        %td= bowler.name
        %td= bowler.usbc_number
        %td= link_to 'Show', bowler
        %td= link_to 'Edit', edit_bowler_path(bowler)
        %td= link_to 'Destroy', bowler, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bowler', new_bowler_path

app/views/bowlers/new.html.haml
%h1 New bowler

= render 'form'

= link_to 'Back', bowlers_path

app/views/bowlers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bowler.name
%p
  %b Usbc number:
  = @bowler.usbc_number

= link_to 'Edit', edit_bowler_path(@bowler)
\|
= link_to 'Back', bowlers_path